### ISSUE TITLE
Rate limit exceeded

### ISSUE THREAD

**Issue by kengetz** [chrislemke/ChatFred#15]
Thanks for the great add-in, but I'm getting an error about my rate limit being exceeded, even though I haven't used ChatGPT at all. My OpenAI dashboard shows no requests for march. Not sure what's up...

**Comment by kengetz** [comment]
Here’s what it says:

You have reached the rate limit. Check your settings in your OpenAl dashboard.

I have the MacGPT app, have used it twice, and it works fine. So I know my account is working appropriately. Thanks!

**Comment by chrislemke** [comment]
Here are some useful links concerning the rate limit:
https://help.openai.com/en/articles/6897202-ratelimiterror
https://help.openai.com/en/articles/6891753-rate-limit-advice

It could be, that the max tokens are set too high. The default for ChatGPT is 4096. You can try adjusting them in the workflow's configuration (*Maximum tokens*).

You could also try the solution I talked about in [this post](https://github.com/chrislemke/ChatFred/issues/12#issuecomment-1462366528). With this, you will get a more detailed error message.

**Comment by dna75** [comment]
Same issue here! My token is set but get the same 'rate limit' warning. I checked my openai credits and have used barely anything.

**Comment by chrislemke** [comment]
Hey! 
I just created a new [release (1.2.0)](https://github.com/chrislemke/ChatFred/releases/tag/v1.2.0). It contains some new features for [troubleshooting](https://github.com/chrislemke/ChatFred#troubleshooting-%EF%B8%8F) maybe this can help you guys solve you issue.

**Comment by kengetz** [comment]
Thanks! Will try it!

**Comment by dna75** [comment]
I installed 1.2.1
I get an error;
[10:10:29.033] ERROR: ChatFred[Run Script] Traceback (most recent call last):
  File "/Users/mymac/stack/Alfred.alfredpreferences/workflows/user.workflow.ECF95AA9-E47F-4F55-854B-09B54347B2ED/src/text_chat.py", line 186, in <module>
    __prompt, __response = ke_chat_request(
                           ^^^^^^^^^^^^^^^^^^
  File "/Users/mymac/stack/Alfred.alfredpreferences/workflows/user.workflow.ECF95AA9-E47F-4F55-854B-09B54347B2ED/src/text_chat.py", line 147, in make_chat_request
    intercept_custom_prompts(prompt)
  File "/Users/mymac/stack/Alfred.alfredpreferences/workflows/user.workflow.ECF95AA9-E47F-4F55-854B-09B54347B2ED/src/text_chat.py", line 98, in intercept_custom_prompts
    last_request_successful = read_from_cache("last_chat_request_successful")
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mymac/stack/Alfred.alfredpreferences/workflows/user.workflow.ECF95AA9-E47F-4F55-854B-09B54347B2ED/src/global_services.py", line 38, in read_from_cache
    data = plistlib.load(plist)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/plistlib.py", line 869, in load
    raise InvalidFileException()
plistlib.InvalidFileException: Invalid file

**Comment by chrislemke** [comment]
Could you check if you have the `~/Library/Application Support/Alfred/Workflow Data/ai.lemke.chatfred/ChatFred_Cache` file?

**Comment by dna75** [comment]
I updated to the latest update 1.2.2 and still get the quota error (the other errors are gone).
I played around with the Maximum token setting but that doesn't make any difference.

Date/Time: 2023-03-15 14:05:04.059271
model: gpt-3.5-turbo
workflow_version: 1.2.2
error_message: You exceeded your current quota, please check your plan and billing details.
