### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by han-ysys** [chrislemke/ChatFred#22]
I had a look at the [troubleshooting section](https://github.com/chrislemke/ChatFred#troubleshooting-%EF%B8%8F)
- [√ ] Yes
- [ ] No

**Describe the bug**
Test with 'cf say it is a test', but nothing happens. Workflow debugger says:
```
[23:09:00.215] ChatFred[Keyword] Processing complete
[23:09:00.217] ChatFred[Keyword] Passing output 'say it is a test' to Run Script
[23:09:00.722] ERROR: ChatFred[Run Script] Traceback (most recent call last):
  File "src/text_chat.py", line 58, in <module>
    def read_from_log() -> list[str]:
TypeError: 'type' object is not subscriptable
[23:09:00.723] ChatFred[Run Script] Processing complete
[23:09:00.723] ChatFred[Run Script] Passing output '' to Large Type
[23:09:00.724] ChatFred[Run Script] Passing output '' to Conditional
[23:09:00.725] ChatFred[Run Script] Passing output '' to Conditional
[23:09:00.725] ChatFred[Conditional] Processing complete
[23:09:00.726] ChatFred[Conditional] Passing output '' to Copy to Clipboard
[23:09:00.726] ChatFred[Copy to Clipboard] Processing complete
[23:09:00.727] ChatFred[Copy to Clipboard] Passing output '' to Conditional
[23:09:00.727] ChatFred[Conditional] Processing complete
[23:09:00.728] ChatFred[Conditional] Passing output '' to Post Notification
```

**To Reproduce**
Trigger ChatFred with 'cf say it is a test'

**Relevant information from the `ChatFred_Error.log` file**
No error log was produced.
ChatFred version: 1.2.1
Alfred version: 5.0.6

**Additional context**
By the way, 'cfi' command works well.

**Comment by chrislemke** [comment]
Hey @han-ysys!
Sorry for this. I already found the bug (at least I hope) and will provide a new release soon. If you want to fix it on your machine you can simply the following code in the `text_chat.py` file.
```python
def read_from_log() -> list[str]:
```  
by:
```python
def read_from_log():
```

Alternatively you can update your Python Version to <= 3.10.

**Comment by chrislemke** [comment]
This [release (1.2.2)](https://github.com/chrislemke/ChatFred/releases/tag/v.1.2.2) should work.

**Comment by chrislemke** [comment]
Hey @CullumAttwell!
Do you get the same error message?

**Comment by CullumAttwell** [comment]
Hi @chrislemke,

I just uninstalled and reintalled via your link and this is the error that came through on the debug viewer: 

`[23:27:58.792] ChatFred[Keyword] Processing complete
[23:27:58.797] ChatFred[Keyword] Passing output 'asdfasdf' to Run Script
[23:27:59.120] ERROR: ChatFred[Run Script] Traceback (most recent call last):
  File "/.../Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BBAFA9DD-4B66-4BDE-8042-BD93A6FE29FA/src/text_chat.py", line 153, in make_chat_request
    openai.ChatCompletion.create(
AttributeError: module 'openai' has no attribute 'ChatCompletion'. Did you mean: 'Completion'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BBAFA9DD-4B66-4BDE-8042-BD93A6FE29FA/src/text_chat.py", line 186, in <module>
    __prompt, __response = make_chat_request(
  File "/...l/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BBAFA9DD-4B66-4BDE-8042-BD93A6FE29FA/src/text_chat.py", line 167, in make_chat_request
    response = exception_response(exception)
  File "/.../Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.BBAFA9DD-4B66-4BDE-8042-BD93A6FE29FA/src/error_handling.py", line 74, in exception_response
    if isinstance(error, openai.error.Timeout):
AttributeError: module 'openai.error' has no attribute 'Timeout'
[23:27:59.130] ChatFred[Run Script] Processing complete
[23:27:59.131] ChatFred[Run Script] Passing output '' to Large Type
[23:27:59.132] ChatFred[Run Script] Passing output '' to Conditional
[23:27:59.133] ChatFred[Run Script] Passing output '' to Conditional
[23:27:59.134] ChatFred[Conditional] Processing complete
[23:27:59.135] ChatFred[Conditional] Passing output '' to Copy to Clipboard
[23:27:59.136] ChatFred[Copy to Clipboard] Processing complete
[23:27:59.137] ChatFred[Copy to Clipboard] Passing output '' to Conditional`

Let me know if there is anything else I can assist with.

Thanks

**Comment by chrislemke** [comment]
Hi @CullumAttwell,
thanks for providing this information. This is a strange error.
```
AttributeError: module 'openai' has no attribute 'ChatCompletion'.
```
Since [`ChatCompletion`](https://platform.openai.com/docs/guides/chat/introduction) obviously does exist I have a bit of the feeling that an old version of the OpenAI packages - for some reason still remains on your machine.

Could you navigate to: `~/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.THE ID OF THE CHATFRED WORKFLOW/src/libs/openai/__init__.py`.

Right at the top you should find: 
```
from openai.api_resources import (
    Audio,
    ChatCompletion,
    Completion,
    Customer,
    Edit,
    Deployment,
    Embedding,
    Engine,
    ErrorObject,
    File,
    FineTune,
    Image,
    Model,
    Moderation,
)
```
If it does not contain `ChatCompletion` we know your machine has the [old package/files](https://github.com/openai/openai-python/blob/a7305833040804f9d071c401e57557ae5ed0d691/openai/__init__.py) and you can simply install the new version. 

Same applies for the `AttributeError: module 'openai.error' has no attribute 'Timeout'` error.

**Comment by CullumAttwell** [comment]
Morning @chrislemke,

Thanks for your response.

I have just tested this out and I can confirm that I have ChatCompletion within the specificed file.

I completed a fresh install from https://alfred.app/workflows/chrislemke/chatfred/ but the issue still persists.

On a side note, I have realised that I am able to use the "cft" part of the worflow (I was unaware of this before) but the "cf" and "cfi" commands still allude me.

**Comment by chrislemke** [comment]
Thanks for the quick update. What error you are getting if you try `cfi`?

**Comment by CullumAttwell** [comment]
```
[09:14:43.118] ChatFred[Keyword] Passing output 'tester' to Run Script
[09:14:43.336] ERROR: ChatFred[Run Script] Traceback (most recent call last):
  File "/.../Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8D40654A-A2DC-483E-87C4-16AF50908560/src/image_generation.py", line 67, in make_request
    response = openai.Image.create(prompt=prompt, n=1, size=f"{size}x{size}")
AttributeError: module 'openai' has no attribute 'Image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8D40654A-A2DC-483E-87C4-16AF50908560/src/image_generation.py", line 85, in <module>
    __response = make_request(get_query(), __size)
  File "/.../Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8D40654A-A2DC-483E-87C4-16AF50908560/src/image_generation.py", line 75, in make_request
    error_message=exception._message,  # type: ignore  # pylint: disable=protected-access
AttributeError: 'AttributeError' object has no attribute '_message'
[09:14:43.348] ChatFred[Run Script] Processing complete
[09:14:43.350] ChatFred[Run Script] Passing output '' to Conditional
[09:14:43.351] ChatFred[Conditional] Processing complete
[09:14:43.352] ChatFred[Conditional] Passing output '' to Large Type
```

**Comment by CullumAttwell** [comment]
You've cracked it! It seems that my mac no longer had Python installed after an update.

Thanks for all your help with this!

**Comment by chrislemke** [comment]
Wow nice! I hope it works now for you?!

**Comment by CullumAttwell** [comment]
Yes - it works splendidly. Thanks for all your work on this!

**Comment by chrislemke** [comment]
Great! You are welcome! Enjoy using it. And please feel free to suggest any new features you would like to have or report any bug you encounter!
