### ISSUE TITLE
No response, just large 💬 emoji

### ISSUE THREAD

**Issue by illus0r** [chrislemke/ChatFred#67]
I had a look at the [troubleshooting section](https://github.com/chrislemke/ChatFred#troubleshooting-%EF%B8%8F)
- [x] Yes
- [ ] No

**Describe the bug**

I used a test request from your website

<img width="200" alt="Screenshot 2023-06-04 at 22 17 57" src="https://github.com/chrislemke/ChatFred/assets/797993/35f667af-0d21-4420-819d-9cd3afcfbff4">

The “stay tuned” message appeared for s moment…

<img width="200" alt="Screenshot 2023-06-04 at 22 18 25" src="https://github.com/chrislemke/ChatFred/assets/797993/96a73244-3850-4233-9a08-35c500894ac7">

…then the Large type splash screen popped up only to display this huge 💬 emoji.

<img width="200" alt="Screenshot 2023-06-04 at 22 18 40" src="https://github.com/chrislemke/ChatFred/assets/797993/f28b41a8-e970-46fc-8e65-a0c0dce2b96a">

**To Reproduce**
1. Uninstall workflow
2. Install again
3. Config the token, leave other configs intact.
4. Try Instruct GPT by typing a “cft” prefix and make sure it works.
5. Try to use chat gpt, get nothing but a large 💬 emoji
6. Make sure the clipboard is empty despite you have the corresponding checkbox on.

**Expected behavior**
To get the chat GPT response in Large type and in the clipboard

**Alfred's debug log**
```
[22:30:20.271] Logging Started...
[22:30:23.262] ChatFred[Script Filter] Queuing argument 'what is Monty Python's second film'
[22:30:23.397] ChatFred[Script Filter] Script with argv 'what is Monty Python's second film' finished
[22:30:23.404] ChatFred[Script Filter] {"variables": {"user_prompt": "what is Monty Python's second film"}, "items": [{"type": "default", "title": "what is Monty Python's second film", "subtitle": "Talk to ChatGPT \ud83d\udcac", "arg": ["400a47b8-030e-11ee-849b-fe9c968c4dab", "what is Monty Python's second film"], "autocomplete": "what is Monty Python's second film", "icon": {"path": "./icon.png"}}]}
[22:30:38.317] ChatFred[Script Filter] Processing complete
[22:30:38.319] ChatFred[Script Filter] Passing output '(
    "400a47b8-030e-11ee-849b-fe9c968c4dab",
    "what is Monty Python's second film"
)' to Run Script
[22:30:38.613] ChatFred[Run Script] Processing complete
[22:30:38.619] ChatFred[Run Script] Passing output 'what is Monty Python's second film' to Conditional
[22:30:38.621] ChatFred[Conditional] Processing complete
[22:30:38.622] ChatFred[Conditional] Passing output 'what is Monty Python's second film' to Conditional
[22:30:38.623] ChatFred[Conditional] Processing complete
[22:30:38.624] ChatFred[Conditional] Passing output 'what is Monty Python's second film' to Conditional
[22:30:38.625] ChatFred[Conditional] Processing complete
[22:30:38.626] ChatFred[Conditional] Passing output 'what is Monty Python's second film' to Run Script
[22:30:38.627] ChatFred[Conditional] Passing output 'what is Monty Python's second film' to Run Script
[22:30:38.659] ChatFred[Run Script] Processing complete
[22:30:38.663] ChatFred[Run Script] Passing output '1' to Conditional
[22:30:38.664] ChatFred[Conditional] Processing complete
[22:30:38.665] ChatFred[Conditional] Passing output '1' to Large Type
[22:30:39.329] ERROR: ChatFred[Run Script] Function: read_from_log took 0.0000 seconds

Function: create_message took 0.0000 seconds

Traceback (most recent call last):
  File "/Users/ivandianov/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.CC85BF05-D3F1-49E0-8293-6EFA50A503B7/src/text_chat.py", line 258, in make_chat_request
    openai.ChatCompletion.create(
AttributeError: module 'openai' has no attribute 'ChatCompletion'. Did you mean: 'Completion'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ivandianov/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.CC85BF05-D3F1-49E0-8293-6EFA50A503B7/src/text_chat.py", line 291, in <module>
    __prompt, __response = make_chat_request(
  File "/Users/ivandianov/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.CC85BF05-D3F1-49E0-8293-6EFA50A503B7/src/text_chat.py", line 56, in timeit_wrapper
    result = func(*args)
  File "/Users/ivandianov/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.CC85BF05-D3F1-49E0-8293-6EFA50A503B7/src/text_chat.py", line 276, in make_chat_request
    error_message=exception._message,  # type: ignore  # pylint: disable=protected-access
AttributeError: 'AttributeError' object has no attribute '_message'
[22:30:39.332] ChatFred[Run Script] Processing complete
[22:30:39.334] ChatFred[Run Script] Passing output '' to Automation Task
[22:30:39.336] ChatFred[Automation Task] Running task 'Identify Frontmost App' with no arguments
[22:30:39.337] ChatFred[Run Script] Passing output '' to Arg and Vars
[22:30:39.339] ChatFred[Arg and Vars] Processing complete
[22:30:39.340] ChatFred[Arg and Vars] Passing output '' to Conditional
[22:30:39.342] ChatFred[Conditional] Processing complete
[22:30:39.343] ChatFred[Conditional] Passing output '' to Copy to Clipboard
[22:30:39.345] ChatFred[Run Script] Passing output '' to Debug
[22:30:39.346] ChatFred[Debug] VARIABLES:{
  always_copy_to_clipboard = "1"
  always_speak = "0"
  api_key = "sk-xxxx"
  cf_aliases = "joke=tell me a joke;"
  chat_gpt_model = "gpt-3.5-turbo"
  chat_max_tokens = ""
  completion_max_tokens = ""
  custom_api_url = ""
  frequency_penalty = "0.0"
  history_length = "3"
  history_type = "search"
  image_size = "512"
  instruct_gpt_model = "text-davinci-003"
  jailbreak_prompt = ""
  loading_indicator_text = "💭 Stay tuned... ChatGPT is thinking"
  paste_response = "0"
  presence_penalty = "0.0"
  save_to_file = "0"
  save_to_file_dir = "/Users/ivandianov"
  show_loading_indicator = "1"
  show_notifications = "1"
  temperature = "0"
  top_p = "1"
  transformation_prompt = "Write the text so that each letter is replaced by its successor in the alphabet."
  user_prompt = "what is Monty Python's second film"
}
RESPONSE:''
[22:30:39.349] ChatFred[Run Script] Passing output '' to Conditional
[22:30:39.351] ChatFred[Conditional] Processing complete
[22:30:39.363] ChatFred[Conditional] Passing output '' to Large Type
[22:30:39.366] ChatFred[Run Script] Passing output '' to Conditional
[22:30:39.770] ChatFred[Automation Task] Processing complete
[22:30:39.787] ChatFred[Automation Task] Passing output 'Alfred Preferences' to Arg and Vars
```

**Relevant information from the `ChatFred_Error.log` file**
No relevant errors in the file

**Additional context**

**Comment by chrislemke** [comment]
Hey @illus0r!
Thanks for your expressive issue. I will investigate it. You did not mask the `api_key` parameter in the log. I replaced it with some `xxx`. But it is still recommended to remove this key from your OpenAI account and create a new one - if that was a valid key.

**Comment by chrislemke** [comment]
It looks there is something fishy with the OpenAI package:

```
AttributeError: module 'openai' has no attribute 'ChatCompletion'. Did you mean: 'Completion'?
```

Have you installed [OpenAI's Python package](https://github.com/openai/openai-python)? Iy should be included in the Workflow. Could you check if you can find `path/to/the/workflow_folder/workflows/user.workflow.some_UUID/src/libs/openai/__init__.py`

and check if it contains:
```python
from openai.api_resources import (
    Audio,
    ChatCompletion,
    Completion,
    Customer,
    Edit,
    Deployment,
    Embedding,
    Engine,
    ErrorObject,
    File,
    FineTune,
    Image,
    Model,
    Moderation,
)
```
Since your error message says: `module 'openai' has no attribute 'ChatCompletion'` it could be that the package is either outdated or not installed.

**Comment by chrislemke** [comment]
Hey @illus0r!
Any updates on your issue? Is it working? Do you need further help?

**Comment by otrai** [comment]
I'm having the same issue, but I deleted and reinstalled ChatFred, so I don't see any error log file and I installed the openai python package.

**Comment by chrislemke** [comment]
> I'm having the same issue, but I deleted and reinstalled ChatFred, so I don't see any error log file and I installed the openai python package.

Usually, you should not need to install OpenAI's Python package since it is part of ChatFred. The installed package is definitely compatible. Maybe you have installed a non-compatible package installed?

**Comment by simonleandergrimm** [comment]
@chrislemke Just flagging that i've got the same issue. I just installed chatfred and only get the 💬. I've added my API key, which should give me access to both gpt 3.5 and gpt 4.

**Comment by simonleandergrimm** [comment]
See debug log:

```
[11:18:05.513] ChatFred[Script Filter] {"variables": {"user_prompt": "Testing if Chatfred is working: Who was Napoleon?"}, "items": [{"type": "default", "title": "Testing if Chatfred is working: Who was Napoleon?", "subtitle": "Talk to ChatGPT \ud83d\udcac", "arg": ["cf2223be-19b4-11ee-9fc2-9e626c78cbf6", "Testing if Chatfred is working: Who was Napoleon?"], "autocomplete": "Testing if Chatfred is working: Who was Napoleon?", "icon": {"path": "./icon.png"}}]}
[11:18:06.933] ChatFred[Script Filter] Processing complete
[11:18:06.940] ChatFred[Script Filter] Passing output '(
    "cf2223be-19b4-11ee-9fc2-9e626c78cbf6",
    "Testing if Chatfred is working: Who was Napoleon?"
)' to Run Script
[11:18:06.983] ChatFred[Run Script] Processing complete
[11:18:06.988] ChatFred[Run Script] Passing output 'Testing if Chatfred is working: Who was Napoleon?' to Conditional
[11:18:06.990] ChatFred[Conditional] Processing complete
[11:18:06.991] ChatFred[Conditional] Passing output 'Testing if Chatfred is working: Who was Napoleon?' to Conditional
[11:18:06.992] ChatFred[Conditional] Processing complete
[11:18:06.993] ChatFred[Conditional] Passing output 'Testing if Chatfred is working: Who was Napoleon?' to Conditional
[11:18:06.995] ChatFred[Conditional] Processing complete
[11:18:06.996] ChatFred[Conditional] Passing output 'Testing if Chatfred is working: Who was Napoleon?' to Run Script
[11:18:06.997] ChatFred[Conditional] Passing output 'Testing if Chatfred is working: Who was Napoleon?' to Run Script
[11:18:07.015] ChatFred[Run Script] Processing complete
[11:18:07.026] ChatFred[Run Script] Passing output '1' to Conditional
[11:18:07.027] ChatFred[Conditional] Processing complete
[11:18:07.029] ChatFred[Conditional] Passing output '1' to Large Type
[11:18:07.712] ERROR: ChatFred[Run Script] Function: read_from_log took 0.0000 seconds

Function: create_message took 0.0000 seconds

Traceback (most recent call last):
  File "/Users/simongrimm/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B6251DFC-9810-438F-8DC3-CB1345372A53/src/text_chat.py", line 258, in make_chat_request
    openai.ChatCompletion.create(
AttributeError: module 'openai' has no attribute 'ChatCompletion'. Did you mean: 'Completion'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/simongrimm/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B6251DFC-9810-438F-8DC3-CB1345372A53/src/text_chat.py", line 291, in <module>
    __prompt, __response = make_chat_request(
  File "/Users/simongrimm/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B6251DFC-9810-438F-8DC3-CB1345372A53/src/text_chat.py", line 56, in timeit_wrapper
    result = func(*args)
  File "/Users/simongrimm/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B6251DFC-9810-438F-8DC3-CB1345372A53/src/text_chat.py", line 276, in make_chat_request
    error_message=exception._message,  # type: ignore  # pylint: disable=protected-access
AttributeError: 'AttributeError' object has no attribute '_message'
[11:18:07.733] ChatFred[Run Script] Processing complete
[11:18:07.734] ChatFred[Run Script] Passing output '' to Automation Task
[11:18:07.736] ChatFred[Automation Task] Running task 'Identify Frontmost App' with no arguments
[11:18:07.737] ChatFred[Run Script] Passing output '' to Arg and Vars
[11:18:07.738] ChatFred[Arg and Vars] Processing complete
[11:18:07.739] ChatFred[Arg and Vars] Passing output '' to Conditional
[11:18:07.740] ChatFred[Conditional] Processing complete
[11:18:07.741] ChatFred[Conditional] Passing output '' to Copy to Clipboard
[11:18:07.742] ChatFred[Run Script] Passing output '' to Debug
[11:18:07.743] ChatFred[Debug] VARIABLES:{
  always_copy_to_clipboard = "1"
  always_speak = "0"
  api_key = "sk-XXXXXXX" # removed API key
  cf_aliases = "joke=tell me a joke;"
  chat_gpt_model = "gpt-3.5-turbo"
  chat_max_tokens = ""
  completion_max_tokens = ""
  custom_api_url = ""
  frequency_penalty = "0.0"
  history_length = "4"
  history_type = "search"
  image_size = "1024"
  instruct_gpt_model = "text-davinci-003"
  jailbreak_prompt = ""
  loading_indicator_text = "💭 Stay tuned... ChatGPT is thinking"
  paste_response = "0"
  presence_penalty = "0.0"
  save_to_file = "0"
  save_to_file_dir = "/Users/simongrimm"
  show_loading_indicator = "1"
  show_notifications = "1"
  temperature = "0"
  top_p = "1"
  transformation_prompt = "Write the text so that each letter is replaced by its successor in the alphabet."
  user_prompt = "Testing if Chatfred is working: Who was Napoleon?"
}
RESPONSE:''
[11:18:07.745] ChatFred[Run Script] Passing output '' to Conditional
[11:18:07.746] ChatFred[Conditional] Processing complete
[11:18:07.747] ChatFred[Conditional] Passing output '' to Large Type
[11:18:07.748] ChatFred[Run Script] Passing output '' to Conditional
[11:18:07.899] ChatFred[Automation Task] Processing complete
[11:18:07.907] ChatFred[Automation Task] Passing output 'Alfred Preferences' to Arg and Vars
```

**Comment by otrai** [comment]
1. identified my issue in the debugger mode for Alfred:

[09:54:52.250] ERROR: ChatFred[Run Script] xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

2. Search for error which lead me to StackExchange solution:
[invalid active developer path](https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a)

After updating to 13.4.1 macOS Ventura, it seems that xcode developer tools were removed and needed to be reinstalled. Note that there is an option to install just the developer tools only and not xcode (see link in #2).
